# The standard PostgreSQL connection URI
db-uri = "postgres://authenticator:1234@localhost:5432/PGMSNGR"

# The database schema to expose as a REST API
db-schemas = "api"

# The database role to use for unauthenticated requests
db-anon-role = "web_anon"

# The secret used to verify JWT tokens (must be at least 32 characters)
jwt-secret = "thisstringissoverysecretextrachars"

# The TCP port to bind the web server (defaults to 3000)
server-port = 3000

# Level of information to be logged (crit, error, warn, info)
log-level = "info"

# Allowed media types for raw output
raw-media-types = "text/html, text/css, image/png"
